version: '3.7'
services:

  web:
    build: .
    ports:
      - "8011:80"
    links:
      - db
    volumes:
      - .:/var/www/html/
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker/consts.php:/var/www/html/classes/consts.php
    environment:
      DB_HOST: db
      DB_NAME: ruian
      DB_USER: ruian
      DB_PASSWORD: ruian

  db:
    hostname: db
    image: mysql:5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: viridiumcz
      MYSQL_DATABASE: ruian
      MYSQL_USER: ruian
      MYSQL_PASSWORD: ruian
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8088:8080"
    links:
      - db

volumes:
  db:
